[project]
name = "idcs-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.10.6",
    "jinja2>=3.1.6",
    "requests>=2.32.4",
]
